### ISSUE TITLE
feat: remove the `steps` keyword from the yaml files

### ISSUE THREAD

**Issue by isacben** [isacben/nugget#7]
The keyword `steps` is not really necessary. It would be better to simplify the yaml files syntax by removing it.

For example:

```yaml
- name: My request
  method: GET
  url: http://todo.app/todos
  http: 200
```
